### ISSUE TITLE
Potential backpack "duplication"

### ISSUE THREAD

**Issue by G3rrus** [nk3nny/LambsDanger#113]
https://github.com/nk3nny/LambsDanger/blob/2789502f69f1c5f8af473dfd58ab155bc3f9a489/addons/danger/functions/fnc_leaderStaticDeploy.sqf#L101

In my own "deploy static weapon qrf" that I wrote recently after Alex2k showed me some code of his + his idea behind it, I came up with code looking almost exactly like this and noticed that due to timing reasons (probably relating to AI being in combat). It would seem that sometimes the putBag action that the assistant is ment to do does not line up with the actual assembly of the weapon that the gunner does (be aware that the backpack of the assistant is technically not needed!). 
- Result: One should in many cases when AI is in combat see that the weapon assembles while the backpack of the assistant appears on the ground somewhere next to it, resuling (once weapon is disassembled again) in 1 gun part and 2 bipod parts being in existence. 

Potential solution that I've found: Actually just making the assistant play the animation (not the action) and removing his backpack instead. 

Example: https://github.com/G3rrus/LMF_Revised/blob/1396db6e4c10226e525f5a6b76ff95454a74c2fa/LMF_R.VR/framework/ai/spawning/fn_staticQRF.sqf#L79

**Comment by nk3nny** [comment]
LOL. Fun example of co development.  You wouldn't also happen to have a repacking function ready to go? Will experiment a little withyour issue! 

-k

**Comment by G3rrus** [comment]
I had/have no interest in them repacking the weapon once deployed in my case so I haven't looked much into it. However I think after working over Alex2ks code and sending mine back to him he took it further and *I think* indeed also included repacking of the weapon in his. Looking at the code that would seem in his case is as simple as deleting the vehicle of the gunner and re-adding the backpacks, probably not quite what you're looking for :p
