### ISSUE TITLE
Potentially creating a lot of empty groups

### ISSUE THREAD

**Issue by G3rrus** [nk3nny/LambsDanger#114]
https://github.com/nk3nny/LambsDanger/blob/69fd16041f03de61efe090138d4a3346cf58436c/addons/wp/functions/fnc_taskAssault.sqf#L29

As the warning on joinSilent states: beware, as brand new group is created for the leaving unit and this could result in the number of groups in a mission growing out of control.
 
Maybe mark group for deletion after he joins his new lonely group? (before he goes back to his old one. 

```group _unit deleteGroupWhenEmpty true;```

**Comment by jokoho48** [comment]
fixed within #112
