### ISSUE TITLE
AI Favour going prone too often.

### ISSUE THREAD

**Issue by zanven42** [nk3nny/LambsDanger#117]
**Is your enhancement related to a problem?**

Playing op's with Lambs the AI flickers often in what sort of state they want to be in between crouch and prone in engagements and sometimes will prone move very long distances which seems more immersion breaking then if they didn't prone enough. (the improvements over time to this issue has been great)

**Solution you'd like:**

AI to go prone less often and when they do have it be more of a commitment instead of switching between prone and crouch multiple times over a short period of time since it would be tiring to do that type of stance switch often and people are lazy :).

**Alternatives you've considered:**

considered the ai don't go prone mod but don't want to lose the cool animations with prone and that will switch the issue from "i need to force stance many units out of prone" into "i need to force units into prone and manage them when they should go back to auto"

**Additional context:**

i think vsing the AI will be more enjoyable overall with less prone.

Even though prone makes the most sense in a lot of scenarios this type of change would impact it does make the AI that are not military (i.e cup insurgents) seem overly good so even having a optional config value on classes to provide a custom bias would be cool.

edit: or have the bias linked to a skill value so the unskilled ai act more dumb?

**Comment by nk3nny** [comment]
Fixed in https://github.com/nk3nny/LambsDanger/pull/160
