### ISSUE TITLE
Player-called support artillery does not work

### ISSUE THREAD

**Issue by Seb105** [nk3nny/LambsDanger#127]
**Mods (complete and add to the following information):**

- **Arma 3:** `1.98 stable` [e.g. 1.00 stable, rc, dev]
- **CBA:** `3.15.1` [e.g. 3.0.0 stable]
- **LAMBS_DANGER:** `2.4.2` [eg. 1.5.0 stable]
  _Make sure to reproduce the issue with only CBA and LAMBS_DANGER on a newly created mission!_

**Description:**

A bug stopping artillery registered as a support using vanilla modules from being usable by the player

**Steps to reproduce:**

- Using the vanilla "support provider" and "support requester" modules, create and register some artillery for a player unit. I used RHS M119a2
- Disable Lambs AI for that group
- Try and call the artillery. The artillery may even aim correctly, but never fires.

**Expected behavior:**

The artillery should fire, and does not. It turns to fire but never actually fires.
Works perfectly in singeplayer

**Where did the issue occur?**

- Dedicated

**Additional context:**

Works perfectly in singleplayer

**Screenshots:**

**Comment by nk3nny** [comment]
Fixed in https://github.com/nk3nny/LambsDanger/pull/160

Thanks for your report Seb105!
