### ISSUE TITLE
Artillery Task

### ISSUE THREAD

**Issue by Juujuu** [nk3nny/LambsDanger#129]
Mods (complete and add to the following information): See link https://docs.google.com/spreadsheets/d/1UsADBVu0honldWiPO-2Bhe8VU4DPiC8pfEjMLQ00o7U/pubhtml

  _Make sure to reproduce the issue with only CBA and LAMBS_DANGER on a newly created mission!_ - Not happening due to server constraints

**Description:**

Task Artillery not working for Headless Client

**Steps to reproduce:**
Open Zeus menu
1.Spawn Unit and Artillery
2.Transfer to Headless Client (Skip this step to see it on client side work first time through)
3.Register as Artillery
4.Check Debug  "Lambs_WP_SideArtilleryHash"
  4.A. Verify you see said unit
  4.B. Verify bottom left that AI shows as Headless Client
5.Task Artillery on a location, 1 salvo, skip adjusting rounds
6.Check Debug again to see said unit removed from the array(If unit remains before shots are fired, then there is an error)
7. Wait until salvo is sent.

**Expected behavior:**

Artillery to shoot

**Where did the issue occur?**

- Dedicated Server

**Comment by jokoho48** [comment]
should have been fixed with #169
