### ISSUE TITLE
Additional Parameters for Camp Module

### ISSUE THREAD

**Issue by hypoxia125** [nk3nny/LambsDanger#135]
Requesting the following parameters for the camp module so that it is more applicable to large bases. CBA's defend can sometimes be buggy.

Requested:

- Ability to change the number of units that camp at the center
- Ability to change the center camp spot's radius

**Comment by nk3nny** [comment]
By default the camp script works as follows: 

If the patrol option is enabled, up to two units will leave the group to patrol the area
If there are buildings nearby there is a 40% chance individual soldiers will enter those buildings 
The rest will move to the center. 

1. I guess a setting to enable/disable using buildings would accomplish much the same
2. You can already do this. It is the second argument of the function. 

```
* Arguments:
* 0: Group performing action, either unit <OBJECT> or group <GROUP>
* 1: Central position camp should be made, <ARRAY>
* 2: Range of patrols and turrets found, default is 50 meters <NUMBER>
* 3: Area the AI Camps in, default [] <ARRAY>
```

Setting up camps and garrisons in larger bases is better achieved with multiple modules/functions and groups. Hence making camp a "macro function" is outside the scope of that function.
