### ISSUE TITLE
fnc_taskReset: return the new group instead of 'true'

### ISSUE THREAD

**Issue by nilsms** [nk3nny/LambsDanger#139]
When using LambsDanger in high level AI scripts or similar it would be convenient to get the new group object after calling taskReset. Typical use case is reassigning a group from a Lambs WP to something else using taskReset. 

So the request boils down to returning "_groupNew" instead of "true" in taskReset.

**Comment by jokoho48** [comment]
After thinking about this I am not totally sure if this is the best move for it in general.
the easiest way for you to get the new group would be to store the leader and get the group from him after that.
so 
```sqf
private _leader = leader _group;
_leader call Lambs_WP_fnc_taskReset;
_group = group _leader;
```

**Comment by nilsms** [comment]
I did consider this approach, but when running in an scheduled environment there is a chance that on your last line: "_group = group _leader;" "_group" will end up as as <NULL-group>.  Not sure if this could occur in a unscheduled environment as well(it's at least a lot less likely). This could be mitigated by getting all the units in the group before calling taskReset and then iterating over the list and getting the first non <NULL-group> object (after taskReset is complete).  Given these issues I think the cleanest approach is to deal with it in taskReset.

**Comment by jokoho48** [comment]
this is impossible when you call the function even in a scheduled environment because call suspends the current script scheduler scope until the function execution is finished. the only way that could happen is if you spawn the function but then you would also get back no return from it.

**Comment by nilsms** [comment]
From my understanding the ARMA 3 scheduler can suspend the execution at any point not just when a script does an explicit sleep or waitUntil. Even when using call the script is not executed atomically. So the result of "leader someGroup" at the beginning of a script is not guaranteed to be equal to "leader someGroup" at the end, even if the script it self does not touch "someGroup" or any of it units.
So if we are unlucky with the timing in regards to the leader being killed, its my understanding that by the time we call "_group = group _leader" at the end the engine might have detected that this unit is dead and removed it from the group, resulting in NULL-group being returned.

**Comment by nk3nny** [comment]
Fixed in https://github.com/nk3nny/LambsDanger/pull/160
