### ISSUE TITLE
cba_settings.sqf not applying changes to values once the server is launched

### ISSUE THREAD

**Issue by MayhemMav** [nk3nny/LambsDanger#146]
**Mods (complete and add to the following information):**

- **Arma 3:** `1.98` 
- **CBA:** `3.5.1` 
- **LAMBS_DANGER:** `2.4.4`
  _Make sure to reproduce the issue with only CBA and LAMBS_DANGER on a newly created mission!_
-I will try this next

**Description:**

This issue pertains to using the userconfig/cba_settings.sqf to apply cba settings at the server level. Changes made within the sqf are not applying once the server is launched, and seem to be reverting to their default values. I'm fairly certain this was not the case in the May update of LAMBS Danger, as I had successfully altered values to suit our needs.

Changes made to other mods are taking effect, this seems to be limited to LAMBS Danger only.

**Steps to reproduce:**

*Recreated the entire array from scratch
*Loaded into several different mission files on different terrains
*Tried setting different values
*Took the .sqf out to see if it still loaded (just in case). Default values loaded for every array, cba_settings.sqf did not load within the rpt log.

**Expected behavior:**

The values within the LAMBS Danger section of the cba array should be called and altered according to what is written in the cba_settings.sqf

**Where did the issue occur?**

- Dedicated 
**Additional context:**

If you wish to discuss further you can add me thru Nkenny's steam, user name is General Mayhem

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

Can supply if needed, the cba_settings.sqf is successfully being loaded according to the .rpt (and changes to other mods are being called).

**Screenshots:**

**Comment by diwako** [comment]
Hey, could you provide us the cba_settings.sqf file? Server RPT would be great as well.

**Comment by MayhemMav** [comment]
[arma3server_x64_2020-07-09_22-19-18.zip](https://github.com/nk3nny/LambsDanger/files/4902843/arma3server_x64_2020-07-09_22-19-18.zip)
Here you go, attached all the testing rpt launches

**Comment by diwako** [comment]
From the logs I do not see the mod loaded. The server cannot enforce CBA settings from unloaded mods. A mission can do that however.

**Comment by MayhemMav** [comment]
its loaded as a -servermod=

**Comment by diwako** [comment]
I take it, the pbo's are in this `@Zeus-MB` folder?

I am not seeing any pbo's loaded from that folder so far.

**Comment by MayhemMav** [comment]
I can almost guarantee they are, as behaviours added through lambs danger such as AI firing GL's at night and so on are working. The values applied properly in previous version of LAMBS, just not this one.

And yea the pbo's are in the @Zeus-MB

**Comment by diwako** [comment]
Please recheck the folder structure of that `@Zeus-MB`. Nothing from this folder is being loaded. the only references found to it are in the start up params and the start up print screen, but not as an addon.

**Comment by diwako** [comment]
As example from my units sever, pbos loaded from server mods do show up in the RPT when they are being mounted
`/opt/fparma/arma3/server/@server/addons/jsrsapex_p_weaponsounds.pbo - unknown`

**Comment by MayhemMav** [comment]
Hmm, well thats weird. The AI definitely seem to be behaving as if the mods are loading. I'll double check everything on my end.

**Comment by diwako** [comment]
It might be that you have spawned them in while in Zeus, thus they are local to you and if you have loaded the mod then it would still work. Granted that is before ACEX might transfer the units to server/hc

**Comment by MayhemMav** [comment]
Ahh yea thats a thought. Strange that it was working before but not now, all I've changed is the PBO's inside @zeus-MB

**Comment by diwako** [comment]
As said, the issue is, nothing from the server side mod gets loaded. Might be a permission issue (tho you have a windows machine, so I guess not) or some other issue.

Prolly should start looking into that first.

**Comment by MayhemMav** [comment]
I'm checking an older .rpt from 2 months ago and the @zeus-MB is showing up in the pbo load order. So yea, looks like something on my end, shame i don't have rpt's from the last few weeks to compare with

**Comment by MayhemMav** [comment]
Thanks for your help, and big ups for your other fine mods too. We use a few (DUI)

**Comment by MayhemMav** [comment]
I'll leave this open so I can update when I find the issue, in case it comes up again

**Comment by MayhemMav** [comment]
Just an update, the pbo's are loading but at the end of the load list (after the arma 3 pbo's). So they're right at the end, not at the end of the mods loaded from -mod=

**Comment by MayhemMav** [comment]
Ok so it looks like the settings are applying now..?? The -servermod= was loading the whole time, the only thing I changed really was putting some of the switches at the end of the batch file -malloc -affinity -hugepages (etc). Previously they were mingled in before the -cfg and -config switches.... so perhaps that was causing an issue? So confused, but it seems to be working as intended now

**Comment by jokoho48** [comment]
is this resolved?

**Comment by MayhemMav** [comment]
yes, sorry ill close it up now. Not sure what fixed it in the end, possibly just doing a system restart.
