### ISSUE TITLE
Task Assault gets stuck on bridges

### ISSUE THREAD

**Issue by IR0NSIGHT** [nk3nny/LambsDanger#148]
AI set to task assault will move slowly (like when set to safe), start glitching into eachother and a lot get stuck near the end of the bridge. Its reproducable with bluefor and opfar group. tested at altis, agia marina, all 4 bridges produce the same result. 
non task assault/normal WP ai will just normally cross the bridge.

**Comment by nk3nny** [comment]
Pathfinding in Arma3 is very finicky. Especially when constantly called (which is exactly what taskAssault does). 

If you need the AI to taskAssault bridges, try to increase the cycle-intervals of the functions.  This issue will be closed in 24hs.
