### ISSUE TITLE
Make task assault smoother and faster

### ISSUE THREAD

**Issue by IR0NSIGHT** [nk3nny/LambsDanger#149]
**Is your enhancement related to a problem?**
i mainly want to use task assault to fastly retreat. Tests show task assault is not significantly faster than vanilla "move".

A clear and concise description of what the enhancement entails. Ex. [...] would improve user experience.
issue 1: 
All ai with task assault move and stop in synchro and stop sharply. they run& shoot 1 second, stop in synchro, start mving again. see video for details.
Issue 2: 
they do not prioritise movement enough. they just appear more recless by not using cover, but are not faster. also see video for example

**Solution you'd like:**

AI that receives task assault and moves WIHTOUT stopping, especially not in synchro. 

**Alternatives you've considered:**

task retreat works well, only the fleeing animation is off. after all i dont want to flee, just retreat a couple hundred meters.

**Additional context:**

I created a test scenario using only cba + lambs. all units are invincible. blue received vanilla move, yellow task assault and orange task retreat. see video for more details.
I added smoke on command to see if obstructing the enemy with smoke yields better results. it does not.

https://youtu.be/2RTDQbntph0

**Comment by nk3nny** [comment]
I'll look into it in the future. One solution would be to write a script, possibly a CBA fsm, which constantly controls which animation the AI runs. As such, it is a little extensive for the current design intentions of LAMBS AI, especially considering that A3 may be approaching the end of its lifetime. 

For now, it is something that can go under the category of future projects.  Unless there are other input, it will be closed within 24h.
