### ISSUE TITLE
Have Guard waypoints be a toggle for Camp Module

### ISSUE THREAD

**Issue by RimmyDownunder** [nk3nny/LambsDanger#161]
Currently, Task Camp functions like so: the group is set on a Sentry waypoint, which will wait until they are able to identify a hostile unit that they can engage. The waypoint will then complete, and they will then be provided 1 of 3 waypoints - Hold, Guard or Search and Destroy. (This explanation provided by Joko, blame him for anything wrong)

This is an okay system but does lead to some oddities noticed in several missions. Primarily related to the Guard waypoint. In vanilla, Guard essential works like a QRF waypoint, with groups being sent off to chase reported enemy forces (since most ops will not make use of the trigger Guard locations). The problem encountered is if the Sentry waypoint is triggered by something other than a player force in its immediate vicinity that it then engages. 

Essentially, we had situations where a fast mover, helicopter or even just a group passing by of a Task Camp would cause the Sentry waypoint to complete. Then a Guard waypoint would be provided, which meant the group at the Camp suddenly decides to start wandering off across the map to chase down the hostiles reported many kilometres away. Result was AI groups behaving in undesirable fashions, abandoning their camps and wandering over the hills. 

Suggested solutions: either have the Guard waypoint option as a toggle choice or have a list of settings like Task Garrison's options for the trigger to end the Garrison. So, an option to choose between Hold, SAD, Guard or Random in the Task Camp module settings.

**Comment by nk3nny** [comment]
Nice idea.

**Comment by nk3nny** [comment]
Fixed in https://github.com/nk3nny/LambsDanger/pull/160
