### ISSUE TITLE
Compatible 1.98 arma version?

### ISSUE THREAD

**Issue by mora145** [nk3nny/LambsDanger#208]
**Mods (complete and add to the following information):**

- **Arma 3:** `1.98.14` 
- **CBA:** `3.15.2` 
- **LAMBS_DANGER:** `2.0` 

**Description:**
Hi guys. 
I have a problem with version 1.98. As I understand there is no version requirement to use it. 
I have the latest CMA (3.15.2). 
Once I start the game, activate the new lambs and start it again, the option to configure addons appears disabled.
Even if I start a new mission everything is still disabled and the other addons stop working. 
I have been using the old Lambs with no problems. But this new update does.

**Steps to reproduce:**

- Start the game
- Activate the addon
- Restart the game

**Screenshots:**
![image](https://user-images.githubusercontent.com/25883820/114492671-034c1300-9be7-11eb-8f41-4aa9f037a5ba.png)

**Comment by Drofseh** [comment]
Arma3 v2.02 is requires for the newest version

**Comment by mora145** [comment]
I see. I figured as much. 
Thanks for the support ;)
