### ISSUE TITLE
Add Dynamic Reinforcement Toggle to ZEN Context Menu Interface

### ISSUE THREAD

**Issue by NoxLibertas** [nk3nny/LambsDanger#214]
**Is your enhancement related to a problem?**

As I've Zeused, I've come across the issue of wanting to quickly toggle the Dynamic Reinforcement variable on a group. But having to find the Configure Group AI module and placing it down on the units usually takes much longer than it needs to. The ZEN Context Menu already in use by LAMBS is the perfect solution to reduce the load on the GM by quickly being able to toggle the variable on and off through the dropdown menu.

**Solution you'd like:**

Add a toggle to the ZEN menu under "Lambs Danger FSM" to enable/disable the Dynamic Reinforcement variable for a group.

**Comment by NoxLibertas** [comment]
In the same token, it would probably be wise to have a toggle Long Range Radio option in there as well. This would assist with setting up Dynamic Reinforcement units quicker and would increase the effectiveness of force multiplier units (like sniper teams, helicopters, etc).

**Comment by NoxLibertas** [comment]
> that option already exists, it is called `Has Radio`

My understanding was that option was for the ability for the AI to use their base radio information share range and not the backpack radio boosted range that the Zeus module "Configure Long-range Radio" seems to provide. I could just be misunderstanding those features. I do think it would be a good addition to add a backpack radio boosted range toggle for a unit, but if that's what that feature already provides, then it makes sense that it's already there. Thanks for the review.

**Comment by jokoho48** [comment]
> 
> 
> > that option already exists, it is called `Has Radio`
> 
> My understanding was that option was for the ability for the AI to use their base radio information share range and not the backpack radio boosted range that the Zeus module "Configure Long-range Radio" seems to provide. I could just be misunderstanding those features. I do think it would be a good addition to add a backpack radio boosted range toggle for a unit, but if that's what that feature already provides, then it makes sense that it's already there. Thanks for the review.

Has Radio == Configure Long-range Radio

**Comment by jokoho48** [comment]
you can see that the variable set in "Configure Long-range Radio": https://github.com/nk3nny/LambsDanger/blob/master/addons/danger/functions/ZeusModules/fnc_moduleSetRadio.sqf#L26
is the same that is set in hasRadio: https://github.com/nk3nny/LambsDanger/blob/master/addons/danger/functions/ZEN/fnc_setHasRadio.sqf#L8

**Comment by jokoho48** [comment]
added in #216
