### ISSUE TITLE
Implement Circle CI?

### ISSUE THREAD

**Issue by jokoho48** [nk3nny/LambsDanger#22]
Do we want to Implement Circle CI to add an Automated and Constant Error check into the project? we could also create automatic Devbuild with that.

**Comment by diwako** [comment]
I have next to no experience with circle ci, I added it to DUI a few days back but I am not even sure if it is set up correctly.

In my opinion, yes, so we can check the code style for consistency as well.

**Comment by jokoho48** [comment]
@diwako would you take care of walking @nk3nny through the process of enabling it in the repo? Then I would do the setup with all the config

**Comment by veteran29** [comment]
Why no GitHub Actions? They are nicely integrated into GitHub also there are ready to use Action recipes under https://github.com/arma-actions

For example workflow that you could base on, take a look at: https://github.com/acemod/ACE3/pull/7207

The only problem I see is that @nk3nny does not seem to be in the beta access. However GitHub is going to release the actions from beta soon and afaik they give the access to beta it quickly too.

You can sign up for the beta here:
https://github.com/features/actions

**Comment by jokoho48** [comment]
the issue I would have with the "official" sqflint version is that it would throw us errors that arent errors.
for example  it does not support _thisEventHandler and also not _x in BIS_fnc_sortBy

**Comment by veteran29** [comment]
You're not forced to use whole workflow file, because of the issue you mentioned ACE has set to ignore the failure status of `sqflint`, it's a nice tool but it could use some updates.

**Comment by jokoho48** [comment]
can you run my version of that? I mean I have a modified version that I hacked together, can I, in theory, run that instead of this one?

**Comment by veteran29** [comment]
@jokoho48 are you on ACE slack? I've discussed with @jonpas the idea of forking the `sqflint` to https://github.com/arma3/ and fixing the issues with it here.

Not sure what was changed in your version but maybe it's worth merging. 

Also you can run anything in GH Actions, the `arma-actions/sqflint@master` is just a wrapper around "official" `sqflint` but nothing holds you from executing it manually via python or creating your own action or whatever.

But if we would have improved version in `https://github.com/arma3/` I would ofc. switch the "official" arma-action to use that.

**Comment by jokoho48** [comment]
will be delayed until nk3nny has access to Actions. until then we will test and try around on my fork of Lambs Danger

**Comment by nk3nny** [comment]
Just checked. I believe actions should be available now.

**Comment by jokoho48** [comment]
yes they are. i will try to look into it after #40

**Comment by nk3nny** [comment]
A funny thing is that after I googled CircleCI once, my youtube is run down with adds for it. (On my cellphone, adblock takes care of the rest)

**Comment by jokoho48** [comment]
implemented with d777da4dfa704a8fe487e2ed98b5c4c1026dd3f8
