### ISSUE TITLE
Error message - (selection of warhead while disembarking?)

### ISSUE THREAD

**Issue by TBartels1** [nk3nny/LambsDanger#266]
I got this error message as the crew of the tank in the distance was disembarking after getting hit. I had Vcom running as well.
![20210619191629_1](https://user-images.githubusercontent.com/37533498/122650665-88e2c680-d134-11eb-88e2-017d22dc5770.jpg)

**Comment by diwako** [comment]
Thanks for the report. Even if the RPT logging is disabled, could you list mods that you were running, possibly also which kind of vehicles were in the scenario.

**Comment by jokoho48** [comment]
should be fixed with #267 in 2.5.2 dev 2 release
