### ISSUE TITLE
Please add more detail to 'area' type waypoints in Waypoints section of Wiki

### ISSUE THREAD

**Issue by Doctor-Butts** [nk3nny/LambsDanger#279]
**Is your enhancement related to a problem?**

The Waypoints portion of the Wiki needs more detail, specifically on the 'area' array areas (garrison, camp, cqb, etc).

**Solution you'd like:**

Define what the parameters are of the 'area' array mentioned in the doc.
It looks like the area should be in the following format, based on what the functions code looks like:
[x area, y area, angle, circle or square]

If circle, last param is false. Opposite for square.

**Comment by diwako** [comment]
Sure, how's this?
https://github.com/nk3nny/LambsDanger/wiki/waypoints

**Comment by jokoho48** [comment]
it is based on https://community.bistudio.com/wiki/inArea Alternative Syntax 3 expect the first entry what is a separate parameter in the function it self

**Comment by Doctor-Butts** [comment]
> 
> 
> Sure, how's this?
> https://github.com/nk3nny/LambsDanger/wiki/waypoints

AWESOME! Thank you!
