### ISSUE TITLE
Infantry in squad with vehicle will repeatedly embark and disembark

### ISSUE THREAD

**Issue by fariparedes** [nk3nny/LambsDanger#280]
- **Arma 3:** `2.04` 
- **CBA:** `3.15.5`
- **LAMBS_DANGER:** `2.5.1`

Sometimes when in combat mode and with a known enemy at a distance, AI will enter a loop of boarding and disembarking from a vehicle, paralyzing that vehicle and obviously keeping the group from actually reaching combat. I suggest that you add some sort of limiter that prevents a unit from trying to get into a vehicle that they just disembarked from for a little while. There's no real reason for AI to climb out of a vehicle and then immediately climb back in anyway.

**Comment by jokoho48** [comment]
douplicate of #262
