### ISSUE TITLE
When firing at helicopters AI are horribly innacurate

### ISSUE THREAD

**Issue by Raptoid** [nk3nny/LambsDanger#296]
**Mods:**

- **Arma 3:** `2.06` 
- **CBA:** `v3.15.6.211004` 
- **LAMBS_DANGER:** `2.5.3` 

**Description:**

If the AI aren't running from helicopters to cover and decide to fire upon it, and it may only be against other AI, they seemingly almost randomly fire their weapons in the air, almost like they are attempting to suppress it yet getting stuck with their aim. They will stop, turn somewhat towards the helicopter, and repeat.

**Steps to reproduce:**
Loaded only CBA and LAMBS_DANGER, tested from editor

**Expected behavior:**

AI can reasonably track a helicopter with their aim without Lamb's Danger.

**Where did the issue occur?**

Editor (Singleplayer)

**Demonstration:**

https://youtu.be/fcuVvyiX3jc

**Comment by nk3nny** [comment]
Improved in https://github.com/nk3nny/LambsDanger/pull/304
