### ISSUE TITLE
Vanilla Zeus Integration

### ISSUE THREAD

**Issue by JamesTheClarke** [nk3nny/LambsDanger#31]
I know from some conversations with nkenny that you guys are working hard on a Zeus Enhanced integration of LAMBS. To broaden the appeal of LAMBS I'd like to request to have the LAMBS WPs also added to vanilla Zeus since some communities still use Achilles or even Ares as their main Zeus enhancement mod or do not employ any enhancement mods at all.

Fully aware that this is probably a lower priority feature request but it would still be neat if it could make it into one of the release-versions. :)

**Comment by nk3nny** [comment]
https://github.com/nk3nny/LambsDanger/issues/9
