### ISSUE TITLE
Randomised AI surrendering

### ISSUE THREAD

**Issue by JamesTheClarke** [nk3nny/LambsDanger#32]
This idea is inspired by a scripting video by DayZMedic: https://www.youtube.com/watch?v=isLmWKeB_QA

It would be neat if LAMBS had a system that allows for a randomized chance of an AI surrendering to the players if its group is no longer combat effective (3/4 casualties sustained). This would provide players more alternatives/problems to deal with regarding AI rather than solving all interactions with bullets. Of course particularly dastardly players can always choose to kill surrendered AI. ;)

Naturally, the script should not guarantee that the AI surrenders all the time. In my view the trigger chance should be between 10-20% of the cases.

**Comment by veteran29** [comment]
If this will be implemented it should be disabled by default imho, this can break missions and cause issues for missions that have own surrendering mechanics. eg. KP Liberation.

**Comment by nk3nny** [comment]
This feature is unfortunately outside the scope of the danger.fsm.  However, once the cba events are in place-- it will be trivial for mission makers and other modders to add their own.  :)

**Comment by JamesTheClarke** [comment]
That's a good point veteran29, didn't think about this liberation game modes.
