### ISSUE TITLE
Use of EventHandlers within danger.fsm

### ISSUE THREAD

**Issue by nk3nny** [nk3nny/LambsDanger#37]
I'll post this as a discussion. What is our stance on the use of eventhandlers within the danger.fsm framework? 

A suggested feature was to increase AI response to explosions. I attempted an FSM level fix to it which works-- meeeh. 

```
//  immediate action - explosion! 
if (_explosive  &&  {damage _this > 0.1}) then {
	[_this,_dangerPos] call lambs_danger_fnc_immediateActionExp;
}; 
```
Instead I have in the steam version experimented with a eventhandler system. Simply triggering off explosionEH: 
https://youtu.be/XNfhSfDbMUE?t=548
~ 9:00 minutes in 

While not strictly speaking FSM level tweaks and an addition. I find this the best solution and well within our scope. _Opinions_? 

**My suggestion**: 
lambs_danger_fnc_immediateActionExp becomes lambs_danger_fnc_immediateActionEH  and is simply triggered on Explosion near eventhandler from vanilla.

**Comment by diwako** [comment]
Depends on what you want to add to it. If it is just a reaction to an explosion which they get damaged by, you need to take into account ACEs hit reactions. By default unit trip if a certain threshold of damage is reached within the ACE medical system. So you gotta check if that unit is running the medical vital loop or not.

In general i am not opposed to this if it is just reactions such as falling down or a more visible flinching or entering combat mode when not in combat. But if it is something like immediate disengagement from combat and other major actions which vanilla AI would not do, then no.

You'd need a XEH to add the eventhandler to all units on all machines, as that EH only fires where the unit is local.
Maybe we can export it into its own addon module add CBA settings to it to control what effects are possible. More freedom for Arma units if they want to use this or not. I do not think as you said yourself that an in FSM solution would work too well

**Comment by nk3nny** [comment]
Would it really need to run on all machines though? The default  explosion eventhandler only really needs to run on machines that have this setting running. 

I am not opposed to making it a different pbo than the danger.fsm. Though it definitely is within the scope of this mod. 

The effect is this: 
* Plays a switchMove animation
* drops unit prone
* CBA waitUntil resets stance after X seconds 

Check the video for an example of the script in action.

**Comment by diwako** [comment]
Just keep in mind `switchMove` is local only

**Comment by nk3nny** [comment]
Will need some investigation or a event workaround.
