### ISSUE TITLE
Unknown enum value: "PRONE"

### ISSUE THREAD

**Issue by mjc4wilton** [nk3nny/LambsDanger#406]
**Mods (complete and add to the following information):**

- **Arma 3:** `2.14 stable`
- **CBA:** `3.17.1`
- **LAMBS_DANGER:** `2.6.0`

**Description:**

RPT and on-screen error caused by an unknown enum value

**Steps to reproduce:**

- Unknown. Only received reports from others about it. Provable issue via bi wiki documentation.

**Expected behavior:**

Error does not occur

**Where did the issue occur?**

Dedicated Multiplayer

**Additional context:**

https://github.com/nk3nny/LambsDanger/blob/9670c56ef4ed48716387974abf278fe3faf89a83/addons/danger/functions/fnc_brainForced.sqf#L55

[BI Wiki](https://community.bistudio.com/wiki/setUnitPosWeak)

**Log Files:**
RPT error:
```
9:50:16 Error in expression <ll lambs_main_fnc_doAssaultSpeed;
_unit setUnitPosWeak (["MIDDLE", "PRONE"] sele>
 9:50:16   Error position: <setUnitPosWeak (["MIDDLE", "PRONE"] sele>
 9:50:16   Error Foreign error: Unknown enum value: "PRONE"
 9:50:16 File z\lambs\addons\danger\functions\fnc_brainForced.sqf..., line 55
 9:50:16 [ACRE] (sys_io) INFO: Pipe error: Read CreateFileA WinErrCode: 2
```

(I think the fix is replacing the enum with `"DOWN"` but I don't have time to read the full code context)

**Comment by jokoho48** [comment]
Wow, this has been in for 3 years, and nobody has noticed until now.

**Comment by nomisum** [comment]
funnily enough i encountered this the first time today as well

**Comment by dedmen** [comment]
I did a big refactor on enum handling. Lots of places were missing validation. Like this one apparently.
