### ISSUE TITLE
Low level fixes for 2.0 pre-release

### ISSUE THREAD

**Issue by nk3nny** [nk3nny/LambsDanger#42]
- [x] Update all code headers
- [x] Small experimentation with f**n_hideInside**  range settings. (generally reduce given new CfgFSMs settings) 
- [x] Experiment with **fn_suppress** to prevent AI from loudly saying _negative_ on failed suppression. (Perhaps a visual check or other 'busy' check) 
- [x] Small fix for **fn_assault**-- to prevent AI from heedlessly following overflying helicopters
- [x] Small YT teaser video

**Comment by diwako** [comment]
Should we also do Wiki entries for the CBA events and such?

**Comment by nk3nny** [comment]
https://github.com/nk3nny/LambsDanger/issues/8

I agree. However, I don't mind documentation lagging a little after the issue is settled. It would be useful if #8 could be filled with simple lists of all known variables and CBA events-- just a list-- then these can be migrated to the Wiki once documentation starts in earnest. 

Sound good?

**Comment by jokoho48** [comment]
those are 2 that are on my list
- [ ] Replace `count > 0` or simular with `isEqualTo []`
- [ ] Replace all "LAMBS_CQB_cleared_" and "lambs_artillery_" with QGVAR/QEGVAR

**Comment by nk3nny** [comment]
- [ ] Testing has shown that 1000 meter comms range may be a little much for vanilla-- i.e., fully seamless integration

- [ ]  Add debug and follow up for fleeing exit state. Is currently invisible

- [ ] Possibly tweak panic slightly. Converting more events from pre-2.0 danger.

**Comment by nk3nny** [comment]
working on **fnc_taskAssault**
Seems to be a bug or problem relating to the 'ATTACK' command. That is it is impossible to override in any way. The order overrules any action made given to the Unit :/

This is what makes the AI static and unresponsive from time to time.

**Comment by nk3nny** [comment]
Seems possible to override this behaviour by having the unit join group Null. INTERESTING.

**Comment by nk3nny** [comment]
Another fix is to 'forget' all current targets via the: https://community.bistudio.com/wiki/forgetTarget command. Not sure a good solution is constantly forgetting all targets.

**Comment by nk3nny** [comment]
- [ ] Implement **fn_taskAsssault**
- [ ] Revisit **fn_taskBuilding** to add flexibility (attacking troops outside buildings)
