### ISSUE TITLE
CBA Setting: "Faction Exclusion"

### ISSUE THREAD

**Issue by G3rrus** [nk3nny/LambsDanger#61]
In my opinion it would be nice to have a CBA setting in which you can define cfgFaction classes which if the AI is part of said defined faction gets excluded from the custom behaviour. 

However that is just one suggestion and really what I mean it just any sort of way to easily disable the addons customized behaviour for large groups of AI at a time while leaving it on for others.

**Comment by nk3nny** [comment]
Hmm.. Not an impossible thing to do. But couldn't you just write an eventhandler which on unit init detects if said unit is part of a given faction then run the disabling variables on it? 

<unit>setVariable ["lambs_danger_disableAI",true]
<group> setVariable ["lambs_danger_dangerAI,"disabled"]

I'll bring the feature for discussion in our next meeting. 

Cheers Garrus!

**Comment by G3rrus** [comment]
Alright cheers! I wasn't saying it was not possible to do something with the setVar like you suggested. I'm merely thinking about conveniences sake if that makes sense. Thinking about it more actually I think just a CBA settings for a global disable of the addon would be a good alternative if the faction exlude is to hard to do.

I'm just suggesting this because I have played and created missions for a lot of groups by now and each one of them were running different AI affecting mods and I know by talking to other mission makers that it is often just the wish of them to disable AI affecting mods quick and easy for certain types of scenarios for various reason. Also not everyone knows the ins and outs of mission making to a degree where making XEHs and setting variables in them is something they can do.
