### ISSUE TITLE
Global AI Subskills via CBA LAMBS Presets

### ISSUE THREAD

**Issue by JamesTheClarke** [nk3nny/LambsDanger#63]
Hi all

I know that this request is most likely out of the immediate scope of the mod but while testing LAMBS for a while I often thought it would be really neat if this was part of the LAMBS AI mod.

Basically, the idea is to add a CBA addons option to preset the global AI subskills for all units spawned or controlled by LAMBS: https://community.bistudio.com/wiki/Arma_3_AI_Skill#Sub-Skills

Currently in order to fiddle with sub-skills players have to use either script solutions (similar to F3 Framework) or a tertiary mod. I'm not sure if those solutions have the potential to conflict with LAMBS somehow. It would be really convenient for Mission Makers to be able to set those sub-skills in LAMBS itself to always be sure that they work as intended and also not having to rely on tertiary solutions from separate developers.

It could also help Zeus players to adjust all AI skill globally on the fly in a single menu if he/she notices that the platoon is having a very hard time. This would be faster and cleaner than having to double click each element and adjusting the parameter bars individually per element to lower AI subkills.

Lemme know what you guys think. ;)

**Comment by nk3nny** [comment]
I'll add this to our list of things to discuss next meeting.  As you know I've been careful not to mess to much with sub-skills, because I find them opaque and tending towards meaninglessness.

Thumbs. It is on our things to discuss list.

-k

**Comment by nk3nny** [comment]
We have discussed this and decided that AI skills toggles are outside the core scope of the project. There may be an additiona LAMBS style pbo in the future.
