### ISSUE TITLE
Meeting 10th of January

### ISSUE THREAD

**Issue by nk3nny** [nk3nny/LambsDanger#65]
As a reminder of things to discuss that have come up internally. 

**For version 2.1+**
1. Rework all Waypoints to be like Vanilla Waypoints
2. Improve Zeus Support
3. Rearm
4. Expanded Callouts and Vocal Coms

**For version 2.0.3+**
1. Revisit vehicle AI
2. Reconsider Building assault & suppress 
3. Again look into FSM movement tweaks

**Comment by nk3nny** [comment]
**Other material for 2.0.3+**

Adding settings for leader assessments: 
 - Units hiding due to presence of tanks
 - Units hiding due to presence of aircraft
 - Units executing group manoeuvres (fn_manoeuvre)
 
Experiment with fn_manoeuvre
Though the current fn_manoeuvre is a work of art *tears in eyes* it may be a little disruptive to certain styles of mission making.  Particularly as it adds a chain of actions which may not be immediately visible to onlookers.  Instead: Consider having a smarter _single_ group action: 

General design - 
 Groups will attempt to suppress enemies in buildings
 Groups will attempt to enter buildings if close
 Groups will move quickly when distance is large  (forceSpeed 24) 
 Groups will move slowly when distance is close  (forceSpeed 3-5)

Possibly extend fn_leaderAssessment
 - Leaders that are stood next to tall buildings may attempt to send a scout to top floor. 
 - Bugfix: Leaders should never send soldiers already mounted in vehicles to man static weapons

**Comment by nk3nny** [comment]
**Wishlist** 
Anyone know an animator with a little free time?  Here are a few animations which would totally, stupendously, improve visualisation and feedback.

Full body animations: 
 - Crouched soldier holds left hand on head/helmet -- weapon is off-shoulder 
 - Prone soldier holds one or both hands on head/helmet
* These would be _fantastic_ for panic reactions

Gestures
- Soldier holds left hand on top of helmet (apparently being afraid) 
- Soldier toggles radio gear (perhaps [this](https://forums.bohemia.net/forums/topic/218790-release-transmitting-radio-animations-for-task-force-radio-advanced-combat-radio-enviroment-2/) guy can be contacted?)
*  First one would be amazing for fn_flee and panic. Second would be great for fn_shareInformation


While I  could think of more variants of the ones noted above, having these simple ones as a starting point would add decisive depth to the mod.

**Comment by nk3nny** [comment]
Also this: 
https://forums.bohemia.net/forums/topic/214949-a-nice-little-self-contained-surrender-script-thing-for-ace/

**Comment by jokoho48** [comment]
@nk3nny i think we talked about this and we didnt wanted this prev

**Comment by nk3nny** [comment]
Absolutely!  I was more interested in this: 
https://community.bistudio.com/wiki/morale

On Tuesday lets make a proper agenda.  This thread more for brainstorming. 

-k

**Comment by nk3nny** [comment]
Also: Future headless client support for some of our scripts
