### ISSUE TITLE
Improve fn_hideInside function when hiding outside 

### ISSUE THREAD

**Issue by nk3nny** [nk3nny/LambsDanger#7]
Improve [fn_hideInside](https://github.com/nk3nny/LambsDanger/blob/master/addons/danger/functions/fnc_hideInside.sqf) by adding checks for nearby 'HIDE', 'BUSHES' or 'TREES'  as per https://community.bistudio.com/wiki/nearestTerrainObjects

**Comment by jokoho48** [comment]
Sneaked that in #6

**Comment by nk3nny** [comment]
Wonderful.  Might want to do 

`private _objs = nearestTerrainObjects [_targetPos, ["HIDE", "TREE", "BUSH"], 7,false,true];`

Slightly extended range, 2d mode, no sorting. 
HIDE, TREE, and BUSH seem to return the best positions in Arma3.  ROCK and ROCKS may return locations inside stones in A3. (Needs testing) .

**Comment by jokoho48** [comment]
yes will do that in next commit
