### ISSUE TITLE
Configure Group AI zeus module cancel button doesn't work

### ISSUE THREAD

**Issue by zharf** [nk3nny/LambsDanger#75]
**Mods (complete and add to the following information):**

- **Arma 3:** `1.96`
- **CBA:** `3.14.0`
- **LAMBS_DANGER:** `2.1.0`

**Description:**
Pressing cancel on Configure Group AI popup causes script errors
```
19:47:15 Error in expression <Vehicle _logic;
}, {
params ["_logic"];
deleteVehicle _logic;
}, {
params ["_log>
19:47:15   Error position: <deleteVehicle _logic;
}, {
params ["_log>
19:47:15   Error deletevehicle: Type Group, expected Object
19:47:15 File z\lambs\addons\danger\functions\ZeusModules\fnc_moduleDisableGroupAI.sqf..., line 34
```

**Steps to reproduce:**

- Place a unit
- Drop Configure Group AI on the unit
- Press cancel

**Expected behavior:**

Dialog closes

**Where did the issue occur?**

- Editor (Singleplayer) / Editor (Multiplayer)

**Comment by jokoho48** [comment]
fixed with https://github.com/nk3nny/LambsDanger/commit/1278327d70401143e675b678b30b837ec5427395
