### ISSUE TITLE
Documentation for unique danger.fsm features

### ISSUE THREAD

**Issue by nk3nny** [nk3nny/LambsDanger#8]
Write documentation for special danger.fsm features, possibly adding videos where relevant.

**Waypoints**
- [x] Seek and Destroy [Enter Buildings]
- [ ] Garrison
- [ ] Patrol
- [ ] Rush
- [ ] Hunt
- [ ] Creep
- [ ] CQB
- [ ] Register Artillery 

**Variables**
- [ ] List of variables added + events 
- [ ] DangerFormation  (_pending name change?_)
- [ ] DangerCode 

**Other**
- [ ] Dynamic Artillery system

**Comment by JamesTheClarke** [comment]
My input regarding this: please add to the in-game tooltips what the AI is targeting/looking for.

Meaning some WPs only actively look for players (Hunt, Creep) and would not work properly if the mission maker uses it to target enemy AI groups.
