### ISSUE TITLE
Squads communication problem

### ISSUE THREAD

**Issue by Alloc186** [nk3nny/LambsDanger#89]
Has something changed recently? Seems like units no more communicate each other or share information on radio. Just curious, thank for info.

Using latest version form steam, playing only SP.

**Comment by nk3nny** [comment]
The amount of information being shared by squads was reduced a few patches back to reduce some of the excessive responses by AI.  (i.e., dropping prone and going into combat mode when 2 kilometers away) 

That said substantial information is still being communicated. Can you describe your problem in more detail? 

-k

**Comment by Alloc186** [comment]
I dont know how to describe it more or better. But I made simple mission, it worked before. Basically units came to help fighting soldiers. In debug code was often somrthing like Unit Knows About XXX.... Now it seems infantry men in distance dont react at all.

[mission.zip](https://github.com/nk3nny/LambsDanger/files/4371279/mission.zip)

**Comment by Alloc186** [comment]
I did some tests and last working version for me is 2.2.1

**Comment by nk3nny** [comment]
Can confirm bug. 

seems to be issue with 

https://github.com/nk3nny/LambsDanger/blob/365b254f265a79934c345e3e904e8b1abbf14ad3/addons/danger/functions/fnc_shareInformation.sqf#L48

Will fix for next version.

**Comment by nk3nny** [comment]
Error is simply that remoteExec does not accept 'local group' as locality check.  Will use leader insteda. 

-k

**Comment by jokoho48** [comment]
fixed with 3ad15a1dc3a0f5a2c1068773e6bce2d564c92a15
