### ISSUE TITLE
Suppress function should be checking are friendly units nearby

### ISSUE THREAD

**Issue by RomanPL79** [nk3nny/LambsDanger#93]
Suppress function is not checking that suppression target is near friendly units. It may cause friendly fire. The function should check is any friendly unit in a proximity ~20 meters of the target to avoid friendly fire. One check at beginning should be enough to fix this issue.

**Comment by RomanPL79** [comment]
Created two pull requests which should solve this issue. (It should be one be one request but I have no idea how to combine it - sorry about that)

https://github.com/nk3nny/LambsDanger/pull/95
https://github.com/nk3nny/LambsDanger/pull/94

**Comment by jokoho48** [comment]
hey, thanks for your PRs. I think that they will not achieve what you plan to get. I can take a look at this later after I have done some more Stringtalbe work :P

**Comment by RomanPL79** [comment]
Hey, thanks for checking it - I hope idea with nearest enemy helped even if I did not analysed code enough ;)
